name: Generate README

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - run: pip install -r requirements.txt

      - name: Generate & Publish README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
          OPENAI_API_KEY: ${{ secrets.SECRET }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/readme.py
